<?php
function cipher_menu(){
  $items = array();
  $items['cipher_form']= array(
    'title'=>'Welcome to Cipher',
    'page callback'=> 'drupal_get_form',
    'page arguments'=> array('cipher_form'),
    'access callback'=> TRUE,
    'type'=> MENU_NORMAL_ITEM,
  );
  $items['cipher_results']= array(
    'title'=> 'Encrypted message',
    'page callback'=> 'show_cipher',
    'access callback'=> TRUE,
    'type'=> MENU_CALLBACK,
  );
  return $items;
}

function cipher_form()
{
  $form['cipher_value']= array(
    '#type'=>'textfield',
    '#title'=> 'Shift Number Value',
    '#description'=> t('Enter the number of places to shift each letter over'),
    '#element_validate'=>array('element_validate_integer_positive'),
    '#required'=> TRUE,
  );
  $form['cipher_direction']= array(
    '#type'=>'textfield',
    '#title'=> 'shift direction',
    '#description'=> 'Enter the word "right" or "left".Ex: "a" with a shift value of 1 and a direction of right would become "b"',
    '#element_validate'=> array('validate_right_left'),
    '#required'=> TRUE,
  );
  $form['cipher_phrase']= array(
    '#type'=>'textfield',
    '#title'=> 'Phrase',
    '#description'=> 'Enter a phrase or sentence to be encoded',
    '#element_validate'=> array('validate_phrase'),
    '#required'=> TRUE,
  );
  $form['cipher_button']= array(
    '#type'=>'submit',
    '#value'=>'Encrypt this message',
  );
  return $form;
}
//Element validation starts:
function validate_right_left($element)
{
  $value = strtolower($element['#value']);
  if($value!= 'left' && $value!= 'right'){
    form_error($element, t('Input must be either "left" or "right"'));
  }
}
function validate_phrase($element){
  $value = $element['#value'];
  if (!preg_match('/^[a-zA-Z .,!?\s]+/', $value)) {
    form_error($element, t('Only word-characters and puntuation are allowed.'));
  }
}
//Element validation ends.

//Beginning of Cipher Logic:
function cipher_form_submit($form, &$form_state)
{
  $cipher_direction = $form_state['values']['cipher_direction'];
  if($cipher_direction=='left'){
    $cipher_value = -intval($form_state['values']['cipher_value']);
  }else{
    $cipher_value = intval($form_state['values']['cipher_value']);
  }
  $cipher_phrase = $form_state['values']['cipher_phrase'];

  $phrase_split= str_split(strtolower($cipher_phrase));
  $alphabet_letters = range('a', 'z');
  $phrase_letters = array();
  $new_letters= array();

  foreach ($phrase_split as $character) {
    if (preg_match('/^[a-zA-Z]+/', $character)) {
      array_push($phrase_letters, $character);
    }
  }
  foreach ($phrase_letters as $letter) {
    $key = array_search ($letter, $alphabet_letters);
   $new_key = $key + $cipher_value;
     if($new_key>25){
         $new_key= $new_key%26;
     }elseif($new_key<0){
         $new_key= 26 -(abs($new_key)%26);
         if($new_key==26){
           $new_key=0;
         }
     }
   $new_letter= $alphabet_letters[$new_key];
   array_push($new_letters, $new_letter);
  }
  $cipher_results= str_replace($phrase_letters,$new_letters, $cipher_phrase);
  $_SESSION['cipher_results']= $cipher_results;
  $form_state['redirect']= 'cipher_results';
}

function show_cipher()
{
  $cipher_results= $_SESSION['cipher_results'];
  return 'Here is your encrypted message: ' .$cipher_results;
}
